var app = require('../config/expressConfig')
const users = require('./users')
const upload = require('./upload')
const systemResource = require('./systemResource')
const acgnConfig = require('./acgnConfig')
const acgnContent = require('./acgnContent')
const tomo = require('./tomo')
const master = require('./master')
app.use(systemResource)
app.use(users)
app.use(upload)
app.use(acgnConfig)
app.use(acgnContent)
app.use(tomo)
app.use(master)
module.exports = app
